### ISSUE TITLE
Errore di battitura

### ISSUE THREAD

**Issue by espositomarco** [Halolegend94/uni_database_appunti#2]
A pagina 65, in basso a sinistra, BlocchiDir=... la seconda "parentesi" è sbagliata.
Grazie per il fantastico lavoro comunque!

Marco Esposito

**Comment by dipietrantonio** [comment]
Grazie per la segnalazione, ho appena corretto la svista e migliorata la notazione delle migliaia! Come è andata oggi?

**Comment by espositomarco** [comment]
Penso bene, non mi è ancora venuto in mente qualcosa che potrei aver sbagliato... In effetti non so se sia una cosa positiva o negativa!

**Comment by dipietrantonio** [comment]
Vabbè il compito era fattibile..segno l'errore come risolto. Grazie ancora, ti ho segnalato tra le persone che hanno aiutato ;)
