### ISSUE TITLE
Errore di battitura

### ISSUE THREAD

**Issue by gceleghin** [Halolegend94/uni_database_appunti#3]
Ciao, grazie mille per questo lavoro che mi è molto utile ora che sto preparando l'orale.
A pagina 4, sotto "1.1.1 Integrità", c'è scritto "vicoli di dominio", da cambiare in "vincoli".

Niente di che, ma tanto che ci siamo... :-)

**Comment by dipietrantonio** [comment]
Grazie mille per il feedback! Correggo subito!
